language: node_js
node_js:
- 14
script: echo "npm test temporarily disabled"
install:
  - npm install --force
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID_AWS
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: eu-central-1
  app: kraken-backend
  env: kraken-backend-environment
  bucket_name: kraken-backend
  on:
    repo: technology-exploration/KRAKEN-backend-opensource
    branch: deploymentDev
  skip_cleanup: 'true'
before_install:
- ls -a
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
  -in .env.enc -out .env.placeholder -d
- ls -a
after_install:
- ls -a