---
defaults:
  run:
    shell: bash
concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: false
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.1.1
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      - run: echo "./node_modules/.bin" >> $GITHUB_PATH
      - run: npm ci
      - run: jest --ci
